### ISSUE TITLE
Crashes on adding exceptions

### ISSUE THREAD

**Issue by Tourniquet88** [hihain/Unigram#1]
In settings, privacy and security, privacy, when you want add an exception on any of those categories (phonenumber, last seen, profil pic, etc) unigram crashes.

You can see the popup for a bit but then its gone.

**Comment by hihain** [comment]
@Tourniquet88 Should work in the current beta. Could you test, please?

**Comment by Tourniquet88** [comment]
Yep that seems be to fixed now :)
