### ISSUE TITLE
Application (version 21.12) crashes after trying to open chat.

### ISSUE THREAD

**Issue by svyatoslavdcode** [hihain/Unigram#42]
Application (version 21.12) crashes after trying to open chat. It crashes immediately, and the chat doesn't even appear on the screen.

**Comment by Dariuosh** [comment]
> Application (version 21.12) crashes after trying to open chat. It crashes immediately, and the chat doesn't even appear on the screen.

U Should Reinstall App Or Reset From Setting

**Comment by staticip555** [comment]
Thank you abaculi for your terrific work, you saved my Lumia from agony.
The app crash in my case was related to the color scheme settings inside the app.
I had chosen the system default color scheme of my mobile, not the app default. This caused the crashes in my case.
After a reset color scheme was the app default scheme and the app was working. After changing to system default of mobile it crashed again. Changing back to app default makes the app work again.

**Comment by wvolkov** [comment]
Could anyone share a compiled appxbundle file of a newer version for tests prior publication at MS Store?

**Comment by staticip555** [comment]
Thanks a lot for fixing the app crash issue based on the windows standard schema with your latest release. Now everything is fine (apart from notifications, which is  a different topic)
