### ISSUE TITLE
Cannot Copy & Paste Messages containing invisible Links

### ISSUE THREAD

**Issue by samij263** [hihain/Unigram#8]
reproduction steps are done in video. 
![Untitled-1](https://user-images.githubusercontent.com/43096208/82995837-6194f500-a019-11ea-9ea9-48eec1a2ac29.gif)

**Comment by hihain** [comment]
@samij263 Can you still reproduce it using the latest beta?

**Comment by samij263** [comment]
I still face crash in version 20.6.52.39

**Comment by samij263** [comment]
> @samij263 Can you still reproduce it using the latest beta?

I still face crash in version 20.6.52.39

**Comment by hihain** [comment]
@samij263: Can you still reproduce this? The video seems to suggest that the attached media is not downloaded. Is that correct?
If you still have the problem, can you forward the message to me on Telegram? Thanks!

**Comment by hihain** [comment]
Reported UnigramDev#1931

**Comment by hihain** [comment]
Reported: UnigramDev#1931

That is the content of the range for the link:
![image](https://user-images.githubusercontent.com/1473059/88477039-1033b400-cf3d-11ea-9163-8b6a9fab5a9d.png)

But actually, any "invisible" Unicode crashes, like "\t" etc.

UWP tries to replace the range.Text with something
`HYPERLINK "https://telegra.ph/file/.....jpg"LINKTEXT`

**Comment by hihain** [comment]
On Edit the invisible link gets replaced by a dot now. @samij263 
Have not found a better solution, yet. Use the bot for editing without losing information. At least it does not crash anymore. ;)

**Comment by samij263** [comment]
Thanks!
